// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebddlqmbvwnzzlsbimza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViZGRscW1idnduenpsc2JpbXphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDIyMzUsImV4cCI6MjA2MjcxODIzNX0.-fKFY3JIdYiDqFdqG9cyyLspgLB0oQ1TnOdpY1XvVBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);